version: "3"
services:
  puti:
    restart: always
    build: .
    container_name: "puti_camera"
    working_dir: "/home/workspace"
    tty: true
    volumes:
      - ./workspace:/home/workspace
    devices:
      - /dev/video0:/dev/video0:mwr
