version: "3"
services:
  python:
    restart: always
    build: .
    container_name: "python3"
    working_dir: "~"
    tty: true
    volumes:
      - ./workspace:~/workspace
    devices:
      - /dev/video0:/dev/video0:mwr
